spring:
    application:
        name: Fetcher
    data:
        redis:
            host: 139.159.239.168
            port: 6379
            database: 1
            lettuce:
                shutdownTimeout: 100ms  # Lettuce 关闭超时时间
                pool:
                    enabled: true       # 启用 Lettuce 连接池
                    maxIdle: 8          # 最大空闲连接数
                    minIdle: 0          # 最小空闲连接数
                    maxActive: 8        # 最大活动连接数
                    maxWait: -1ms       # 最大等待时间
                    timeBetweenEvictionRuns: 30000ms # 连接池清理间隔时间
server:
    port: 8080
